services:
  autoservicesb_api:
    image: proffernando/autoservicesb
    ports:
      - "80:8080"
    depends_on:
      - servico_banco
    networks:
      - autoservicesbnet

  servico_banco:
    image: postgres:17.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/home/ubuntu/dados
    networks:
      - autoservicesbnet

networks:
  autoservicesbnet:
volumes:
  pgdata: